url: "https://cka39758.us-east-1.snowflakecomputing.com"
user: "gpickney"
# snowflake connection options
options:
  - "sfUrl": url,
  - "sfUser": user,
  - "sfPassword": get_password(),
  - "sfDatabase": "USER_GPICKNEY",
  - "sfSchema": "PUBLIC",
  - sfWarehouse": "INTERVIEW_WH"
