USE USER_GPICKNEY.PUBLIC;

CREATE VIEW IF NOT EXISTS DELAY_REASONS_BY_AIRPORT AS SELECT
  -- if delay occurred, then all delay reason columns are >=0 with reason for delay
  COUNT(NULLIFZERO(AIR_SYSTEM_DELAY)) AS AIR_SYSTEM_DELAY_COUNT,
  COUNT(NULLIFZERO(SECURITY_DELAY)) AS SECURITY_DELAY_COUNT,
  COUNT(NULLIFZERO(AIRLINE_DELAY)) AS AIRLINE_DELAY_COUNT,
  COUNT(NULLIFZERO(LATE_AIRCRAFT_DELAY)) AS LATE_AIRCRAFT_DELAY_COUNT,
  COUNT(NULLIFZERO(WEATHER_DELAY)) AS WEATHER_DELAY_COUNT
  a.AIRPORT
FROM UNPIVOTED_AIRPORT_FLIGHTS u
JOIN AIRPORTS a ON a.IATA_CODE = u.AIRPORT
GROUP BY a.AIRPORT
ORDER BY a.AIRPORT ASC;
