USE USER_GPICKNEY.PUBLIC;

DROP VIEW IF EXISTS ON_TIME_PERCENTAGE_AIRLINE_2015;
CREATE VIEW IF NOT EXISTS ON_TIME_PERCENTAGE_AIRLINE_2015 AS SELECT
  AIRLINE,
  1 - (NUMBER_OF_DELAYS/NUMBER_OF_FLIGHTS) as ON_TIME_PERCENTAGE
FROM (
  SELECT
    SUM(1) AS NUMBER_OF_FLIGHTS,
    SUM(
      CASE
        WHEN DEPARTURE_TIME > SCHEDULED_DEPARTURE OR ARRIVAL_TIME > SCHEDULED_ARRIVAL THEN 1
        ELSE 0
      END
    ) as NUMBER_OF_DELAYS,
    a.AIRLINE
  FROM FLIGHTS f
  JOIN AIRLINES a ON a.IATA_CODE = f.AIRLINE
  WHERE YEAR = 2015
  GROUP BY a.AIRLINE
  ORDER BY a.AIRLINE ASC
) FLIGHT_DELAY_INFO;