USE USER_GPICKNEY.PUBLIC;

DROP VIEW IF EXISTS DELAYS_BY_AIRLINE;
CREATE VIEW IF NOT EXISTS DELAYS_BY_AIRLINE AS SELECT
  SUM(1) AS NUMBER_OF_DELAYS,
  a.AIRLINE
FROM FLIGHTS f
JOIN AIRLINES a ON a.IATA_CODE = f.AIRLINE
WHERE DEPARTURE_TIME > SCHEDULED_DEPARTURE OR ARRIVAL_TIME > SCHEDULED_ARRIVAL
GROUP BY a.AIRLINE
ORDER BY a.AIRLINE ASC;