USE USER_GPICKNEY.PUBLIC;

DROP VIEW IF EXISTS NUMBER_UNIQUE_ROUTES_AIRLINE;
CREATE VIEW IF NOT EXISTS NUMBER_UNIQUE_ROUTES_AIRLINE AS SELECT
  a.AIRLINE,
  UNIQUE_ROUTE_LIST,
  ARRAY_SIZE(UNIQUE_ROUTE_LIST) AS NUMBER_OF_UNIQUE_ROUTES
FROM (
  SELECT
    AIRLINE,
    ARRAY_AGG(DISTINCT(CONCAT_WS('->', ORIGIN_AIRPORT, DESTINATION_AIRPORT))) as UNIQUE_ROUTE_LIST
  FROM FLIGHTS
  GROUP BY AIRLINE
) u
JOIN AIRLINES a ON a.IATA_CODE = u.AIRLINE
ORDER BY a.AIRLINE ASC;