USE USER_GPICKNEY.PUBLIC;

CREATE VIEW IF NOT EXISTS MONTHLY_AGG_FLIGHTS_AIRLINE AS
SELECT
  COUNT(1) AS NUMBER_OF_FLIGHTS,
  a.AIRLINE,
  MONTH
FROM FLIGHTS f
JOIN AIRLINES a ON a.IATA_CODE = f.AIRLINE
GROUP BY a.AIRLINE, MONTH
ORDER BY a.AIRLINE ASC;

CREATE VIEW IF NOT EXISTS MONTHLY_AGG_FLIGHTS_AIRPORT AS
SELECT
  COUNT(1) AS NUMBER_OF_FLIGHTS,
  a.AIRPORT,
  MONTH
FROM UNPIVOTED_AIRPORT_FLIGHTS u
JOIN AIRPORTS a ON a.IATA_CODE = u.AIRPORT
GROUP BY MONTH, a.AIRPORT
ORDER BY a.AIRPORT ASC;
