USE USER_GPICKNEY.PUBLIC;

CREATE VIEW IF NOT EXISTS CANCELLATIONS_REASONS_BY_AIRPORT AS SELECT
  COUNT(1) AS NUMBER_OF_CANCELLATIONS,
  CANCELLATION_REASON,
  a.AIRPORT
FROM UNPIVOTED_AIRPORT_FLIGHTS u
JOIN AIRPORTS a ON a.IATA_CODE = u.AIRPORT
WHERE CANCELLED = 1
GROUP BY a.AIRPORT, CANCELLATION_REASON
ORDER BY a.AIRPORT ASC;
