USE USER_GPICKNEY.PUBLIC;

-- UNPIVOTED AIRPORT VIEW FOR USE IN REPORTS BY AIRPORT
DROP VIEW IF EXISTS UNPIVOTED_AIRPORT_FLIGHTS;
CREATE VIEW IF NOT EXISTS UNPIVOTED_AIRPORT_FLIGHTS AS
SELECT
  FLIGHT_NUMBER,
  CANCELLED,
  CANCELLATION_REASON,
  AIR_SYSTEM_DELAY,
  SECURITY_DELAY,
  AIRLINE_DELAY,
  LATE_AIRCRAFT_DELAY,
  WEATHER_DELAY,
  DEPARTURE_TIME,
  SCHEDULED_DEPARTURE,
  ARRIVAL_TIME,
  SCHEDULED_ARRIVAL,
  AIRPORT, // IATA_CODE
  MONTH
FROM FLIGHTS
UNPIVOT(AIRPORT for AIRPORT_TYPE in (ORIGIN_AIRPORT, DESTINATION_AIRPORT));
